name: check_list_app
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^7.0.1
  flutter_riverpod: ^2.0.0
  flutter_secure_storage: ^5.0.0
  flutter_flavorizr: ^2.2.3
  syncfusion_flutter_charts: ^26.1.35
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  intl: ^0.19.0
  mockito: ^5.4.4
  google_fonts: ^6.2.1
  firebase_core: ^2.30.0
  firebase_database: ^10.5.7
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  loading_animation_widget: ^1.2.1
  dio: ^5.4.3+1
  logger: ^2.3.0
  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  coverage: ^1.8.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/
