name: Flutter SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'  # Specify the Flutter version
        channel: 'stable'
        architecture: 'x64'

    - name: Install dependencies
      run: flutter pub get

    # - name: Run tests with coverage
    #   run: |
    #     flutter test --coverage
    #     genhtml coverage/lcov.info -o coverage/

    - name: Install SonarQube scanner
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner-cli-4.6.2.2472-linux.zip
        mv sonar-scanner-4.6.2.2472-linux sonar-scanner
        export PATH=$PATH:`pwd`/sonar-scanner/bin

    - name: Run SonarQube analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=check-list-app \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://152.42.216.45 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

