name: SonarQube Scan

on:
  push:
    branches:
      - develop

jobs:
  sonarQube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.sources=lib \
          -Dsonar.host.url=http://your_droplet_ip:9000 \
          -Dsonar.login=$SONAR_TOKEN
