# name: SonarQube Scan

# on:
#   push:
#     branches:
#       - develop

# jobs:
#   sonarQube:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: sonarsource/sonarqube-scan-action@master
#       - name: SonarQube Scan
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         run: |
#           sonar-scanner \
#           -Dsonar.projectKey=check-list-app \
#           -Dsonar.sources=lib \
#           -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
#           -Dsonar.login=${{ secrets.SONAR_TOKEN }}

# name: SonarQube Scan

# on:
#   push:
#     branches:
#       - develop

# jobs:
#   build:
#     name: Build and analyze
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
#       - uses: sonarsource/sonarqube-scan-action@master
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#       # If you wish to fail your job when the Quality Gate is red, uncomment the
#       # following lines. This would typically be used to fail a deployment.
#       # - uses: sonarsource/sonarqube-quality-gate-action@master
#       #   timeout-minutes: 5
#       #   env:
#       #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

name: SonarQube Scan

on:
  push:
    branches:
      - develop

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          mv sonar-scanner-4.8.0.2856-linux sonar-scanner
          echo "SONAR_SCANNER_HOME=$(pwd)/sonar-scanner" >> $GITHUB_ENV
          echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run SonarQube Scan
        env:
          SONAR_HOST_URL: 178.128.29.159
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=check-list-app \
          -Dsonar.host.url=178.128.29.159 \
          -Dsonar.sources=lib \
          -Dsonar.login=$SONAR_TOKEN
